services:
  backend:
    build: ./backend
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      telegram_bot:
        condition: service_started
      cache:
        condition: service_started
      backend_db:
        condition: service_healthy

  backend_db:
    image: postgres:14-alpine
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s      
      timeout: 5s     
      retries: 5  
      start_period: 10s 
  
  telegram_bot:
    build: ./telegram_bot
    container_name: telegram_bot
    env_file:
     - .env
    restart: always

  cache:
    image: redis:7-alpine
    restart: always
    
volumes:
  postgres_data: